# Generated by Django 4.0.2 on 2022-03-06 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('healthy', 'This plant is healthy'), ('sick', 'This plant is sick'), ('dry', 'This plant is dry'), ('drown', 'This plant is drown')], default='Healthy', max_length=32),
        ),
        migrations.AddField(
            model_name='plant',
            name='sickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApi.sickness'),
        ),
    ]
