# Generated by Django 4.0.2 on 2022-03-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0002_sickness_plant_status_plant_sickness'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='blooming_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='blooming_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='repot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='sunshine',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
