# Generated by Django 4.0.2 on 2022-05-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0007_alter_plant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='blooming_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='blooming_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='repot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunshine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
