# Generated by Django 4.0.2 on 2022-06-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0012_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApi.plant'),
        ),
    ]
