# Generated by Django 4.0.2 on 2022-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0013_task_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='blooming_duration',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='sickness',
        ),
        migrations.AlterField(
            model_name='plant',
            name='blooming_time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='room',
            field=models.CharField(choices=[('living', 'Salon'), ('bedroom', 'Chambre'), ('kitchen', 'Cuisine'), ('study', 'Bureau'), ('bathroom', 'Salle de bain'), ('balcony', 'Balcon'), ('terrace', 'Terrasse')], default='living', max_length=120),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('healthy', 'Cette plante est en bonne santée.'), ('sick', 'Cette plante est malade.'), ('dry', 'Cette plante est asséchée.'), ('drown', 'Cette plante est trop arrosée.')], default='Healthy', max_length=120),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunshine',
            field=models.CharField(choices=[('direct_sunlight', 'Lumière directe'), ('indirect_sunlight', 'Lumière indirecte'), ('shady', 'Ombragé')], default='direct_sunlight', max_length=120),
        ),
    ]
