# Generated by Django 4.0.2 on 2022-06-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0016_alter_plant_room_alter_plant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='room',
            field=models.CharField(choices=[('Salon', 'Salon'), ('Chambre', 'Chambre'), ('Cuisine', 'Cuisine'), ('Bureau', 'Bureau'), ('Salle de bain', 'Salle de bain'), ('Balcon', 'Balcon'), ('Terrasse', 'Terrasse')], default='living', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('healthy', 'Cette plante est en bonne santée.'), ('sick', 'Cette plante est malade.'), ('dry', 'Cette plante est asséchée.'), ('drown', 'Cette plante est trop arrosée.')], default='Healthy', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunshine',
            field=models.CharField(choices=[('directSunlight', 'Lumière directe'), ('indirectSunlight', 'Lumière indirecte'), ('shady', 'Ombragé')], default='directSunlight', max_length=120, null=True),
        ),
    ]
