# Generated by Django 4.0.2 on 2022-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0017_alter_plant_room_alter_plant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('Saine', 'Cette plante est en bonne santée.'), ('Malade', 'Cette plante est malade.'), ('Assoifée', 'Cette plante est asséchée.'), ('Trop humide', 'Cette plante est trop arrosée.')], default='Healthy', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunshine',
            field=models.CharField(choices=[('Directe', 'Lumière directe'), ('Indirecte', 'Lumière indirecte'), ('Ombragé', 'Ombragé')], default='directSunlight', max_length=120, null=True),
        ),
    ]
