# Generated by Django 4.0.2 on 2022-06-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0019_plant_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='repot',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
