# Generated by Django 4.0.2 on 2022-06-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0020_alter_plant_repot_alter_plant_watering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemetrics',
            name='box',
        ),
        migrations.AddField(
            model_name='housemetrics',
            name='date',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='housemetrics',
            name='fine_particle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='housemetrics',
            name='soil_humidity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='housemetrics',
            name='co2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='housemetrics',
            name='humidity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='housemetrics',
            name='temperature',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
