# Generated by Django 4.0.2 on 2022-06-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0021_remove_housemetrics_box_housemetrics_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemetrics',
            name='box_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
