# Generated by Django 4.0.2 on 2022-06-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0022_housemetrics_box_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plantRelqted',
            field=models.BooleanField(default=False),
        ),
    ]
