# Generated by Django 4.0.2 on 2022-06-30 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0023_task_plantrelqted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='plantRelqted',
            new_name='plant_related',
        ),
    ]
