# Generated by Django 4.0.2 on 2022-07-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApi', '0024_rename_plantrelqted_task_plant_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sensor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
